### ISSUE TITLE
Doesn't work with openapi-spec-validator 0.5.0

### ISSUE THREAD

**Issue by jacobtomlinson** [elemental-lf/k8s-crd-resolver#1]
Thanks for making this tool, it's really useful.

It looks like `openapi-spec-validator` 0.5.0 was released today and now we are seeing errors.

```python-traceback
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/bin/k8s-crd-resolver", line 33, in <module>
    sys.exit(load_entry_point('k8s-crd-resolver==0.10.0', 'console_scripts', 'k8s-crd-resolver')())
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/k8s_crd_resolver/__init__.py", line 124, in main
    resolved_schema = parse_and_resolve(version['schema']['openAPIV3Schema'],
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/k8s_crd_resolver/__init__.py", line 72, in parse_and_resolve
    parser = ResolvingParser(openapi_spec_f.name, backend='openapi-spec-validator')
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/prance/__init__.py", line 291, in __init__
    BaseParser.__init__(self, url=url, spec_string=spec_string, lazy=lazy, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/prance/__init__.py", line 116, in __init__
    self.parse()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/prance/__init__.py", line 146, in parse
    self._validate()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/prance/__init__.py", line 322, in _validate
    BaseParser._validate(self)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/prance/__init__.py", line 185, in _validate
    validator(parsed)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/prance/__init__.py", line 229, in _validate_openapi_spec_validator
    from openapi_spec_validator import validate_v2_spec, validate_v3_spec
ImportError: cannot import name 'validate_v2_spec' from 'openapi_spec_validator' (/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/openapi_spec_validator/__init__.py)
Traceback (most recent call last):
  File "/home/runner/work/dask-kubernetes/dask-kubernetes/ci/pre-commit-crd.py", line 93, in <module>
    main(*sys.argv)
  File "/home/runner/work/dask-kubernetes/dask-kubernetes/ci/pre-commit-crd.py", line 89, in main
    run_action(changed_file, temp_dir, crd_path, output_paths)
  File "/home/runner/work/dask-kubernetes/dask-kubernetes/ci/pre-commit-crd.py", line 39, in run_action
    run_generate(
  File "/home/runner/work/dask-kubernetes/dask-kubernetes/ci/pre-commit-crd.py", line 26, in run_generate
    subprocess.run(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['k8s-crd-resolver', '-r', '-j', 'dask_kubernetes/operator/customresources/daskjob.patch.yaml', 'dask_kubernetes/operator/customresources/daskjob.yaml', '/tmp/tmphf74sgk4/daskjob.yaml']' returned non-zero exit status 1.
```

**Comment by jacobtomlinson** [comment]
On digging a little deeper it seems this error is coming from prance.

xref https://github.com/RonnyPfannschmidt/prance/issues/131

**Comment by elemental-lf** [comment]
Workarounded by https://github.com/elemental-lf/k8s-crd-resolver/commit/9f14f89c47197cf2be5000c9e69ab775e818341d for the time being. Thanks!
